# Generated by Django 6.0 on 2025-12-30 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(choices=[('Maths', 'Maths'), ('English', 'English'), ('Physics', 'Physics'), ('Chemistry', 'Chemistry')], max_length=20)),
                ('year', models.IntegerField()),
                ('total_questions', models.IntegerField(default=50)),
                ('score', models.IntegerField()),
                ('percentage', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
